<?php if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_55d5fec1360ee',
	'title' => 'Company Info',
	'fields' => array (
		array (
			'key' => 'field_582c9a5ebb750',
			'label' => 'General',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56fb0575bd9a7',
			'label' => 'Country',
			'name' => 'country',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'US' => 'United States of America',
				'CA' => 'Canada',
				'AU' => 'Australia',
				'UK' => 'United Kingdom',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
			'return_format' => 'value',
		),
		array (
			'key' => 'field_55d5fec08f163',
			'label' => 'Address Line 1',
			'name' => 'address_line_1',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-text field_key-field_55d5fec08f163',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55d5fef88f165',
			'label' => 'City',
			'name' => 'city',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 20,
				'class' => 'field_type-text field_key-field_55d5fef88f165',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55d5ff188f166',
			'label' => 'State',
			'name' => 'us_state',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56fb0575bd9a7',
						'operator' => '==',
						'value' => 'US',
					),
				),
			),
			'wrapper' => array (
				'width' => '25',
				'class' => 'field_type-select field_key-field_55d5ff188f166',
				'id' => '',
			),
			'choices' => array (
				'AL' => 'Alabama',
				'AK' => 'Alaska',
				'AS' => 'American Samoa',
				'AZ' => 'Arizona',
				'AR' => 'Arkansas',
				'CA' => 'California',
				'CO' => 'Colorado',
				'CT' => 'Connecticut',
				'DE' => 'Delaware',
				'DC' => 'District of Columbia',
				'FL' => 'Florida',
				'GA' => 'Georgia',
				'HI' => 'Hawaii',
				'ID' => 'Idaho',
				'IL' => 'Illinois',
				'IN' => 'Indiana',
				'IA' => 'Iowa',
				'KS' => 'Kansas',
				'KY' => 'Kentucky',
				'LA' => 'Louisiana',
				'ME' => 'Maine',
				'MD' => 'Maryland',
				'MA' => 'Massachusetts',
				'MI' => 'Michigan',
				'MN' => 'Minnesota',
				'MS' => 'Mississippi',
				'MO' => 'Missouri',
				'MT' => 'Montana',
				'NE' => 'Nebraska',
				'NV' => 'Nevada',
				'NH' => 'New Hampshire',
				'NJ' => 'New Jersey',
				'NM' => 'New Mexico',
				'NY' => 'New York',
				'NC' => 'North Carolina',
				'ND' => 'North Dakota',
				'OH' => 'Ohio',
				'OK' => 'Oklahoma',
				'OR' => 'Oregon',
				'PA' => 'Pennsylvania',
				'RI' => 'Rhode Island',
				'SC' => 'South Carolina',
				'SD' => 'South Dakota',
				'TN' => 'Tennessee',
				'TX' => 'Texas',
				'UT' => 'Utah',
				'VT' => 'Vermont',
				'VA' => 'Virginia',
				'WA' => 'Washington',
				'WV' => 'West Virginia',
				'WI' => 'Wisconsin',
				'WY' => 'Wyoming',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_56fb05d6bd9a8',
			'label' => 'Province',
			'name' => 'ca_state',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56fb0575bd9a7',
						'operator' => '==',
						'value' => 'CA',
					),
				),
			),
			'wrapper' => array (
				'width' => 25,
				'class' => 'field_type-select field_key-field_55d5ff188f166',
				'id' => '',
			),
			'choices' => array (
				'AB' => 'Alberta',
				'BC' => 'British Columbia',
				'MB' => 'Manitoba',
				'NB' => 'New Brunswick',
				'NF' => 'Newfoundland',
				'NT' => 'Northern Territory',
				'NS' => 'Nova Scotia',
				'ON' => 'Ontario',
				'PE' => 'Prince Edward Island',
				'QC' => 'Quebec',
				'SK' => 'Saskatchewan',
				'YT' => 'Yukon',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
			'return_format' => 'value',
		),
		array (
			'key' => 'field_56fb05d8bd9a9',
			'label' => 'State',
			'name' => 'au_state',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56fb0575bd9a7',
						'operator' => '==',
						'value' => 'AU',
					),
				),
			),
			'wrapper' => array (
				'width' => 25,
				'class' => 'field_type-select field_key-field_55d5ff188f166',
				'id' => '',
			),
			'choices' => array (
				'NSW' => 'New South Wales',
				'QLD' => 'Queensland',
				'SA' => 'South Australia',
				'TAS' => 'Tasmania',
				'VIC' => 'Victoria',
				'ACT' => 'Australian Capital Territory',
				'JBT' => 'Jervis Bay Territory',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
			'return_format' => 'value',
		),
		array (
			'key' => 'field_57aa0e2fafc17',
			'label' => 'Postcode Area',
			'name' => 'postcode_area',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56fb0575bd9a7',
						'operator' => '==',
						'value' => 'UK',
					),
				),
			),
			'wrapper' => array (
				'width' => 25,
				'class' => 'field_type-select field_key-field_55d5ff188f166',
				'id' => '',
			),
			'choices' => array (
				'Aberdeen' => 'Aberdeen',
				'St Albans' => 'St Albans',
				'Birmingham' => 'Birmingham',
				'Bath' => 'Bath',
				'Blackburn' => 'Blackburn',
				'Bradford' => 'Bradford',
				'Bournemouth' => 'Bournemouth',
				'Bolton' => 'Bolton',
				'Brighton' => 'Brighton',
				'Bromley' => 'Bromley',
				'Bristol' => 'Bristol',
				'Belfast' => 'Belfast',
				'Carlisle' => 'Carlisle',
				'Cambridge' => 'Cambridge',
				'Cardiff' => 'Cardiff',
				'Chester' => 'Chester',
				'Chelmsford' => 'Chelmsford',
				'Colchester' => 'Colchester',
				'Croydon' => 'Croydon',
				'Canterbury' => 'Canterbury',
				'Coventry' => 'Coventry',
				'Crewe' => 'Crewe',
				'Dartford' => 'Dartford',
				'Dundee' => 'Dundee',
				'Derby' => 'Derby',
				'Dumfries' => 'Dumfries',
				'Durham' => 'Durham',
				'Darlington' => 'Darlington',
				'Doncaster' => 'Doncaster',
				'Dorchester' => 'Dorchester',
				'Dudley' => 'Dudley',
				'East London' => 'East London',
				'East Central London' => 'East Central London',
				'Edinburgh' => 'Edinburgh',
				'Enfield' => 'Enfield',
				'Exeter' => 'Exeter',
				'Falkirk' => 'Falkirk',
				'Blackpool' => 'Blackpool',
				'Glasgow' => 'Glasgow',
				'Gloucester' => 'Gloucester',
				'Guildford' => 'Guildford',
				'Harrow' => 'Harrow',
				'Huddersfield' => 'Huddersfield',
				'Harrogate' => 'Harrogate',
				'Hemel Hempstead' => 'Hemel Hempstead',
				'Hereford' => 'Hereford',
				'Outer Hebrides' => 'Outer Hebrides',
				'Hull' => 'Hull',
				'Halifax' => 'Halifax',
				'Ilford' => 'Ilford',
				'Ipswich' => 'Ipswich',
				'Inverness' => 'Inverness',
				'Kilmarnock' => 'Kilmarnock',
				'Kingston upon Thames' => 'Kingston upon Thames',
				'Kirkwall' => 'Kirkwall',
				'Kirkcaldy' => 'Kirkcaldy',
				'Liverpool' => 'Liverpool',
				'Lancaster' => 'Lancaster',
				'Llandrindod Wells' => 'Llandrindod Wells',
				'Leicester' => 'Leicester',
				'Llandudno' => 'Llandudno',
				'Lincoln' => 'Lincoln',
				'Leeds' => 'Leeds',
				'Luton' => 'Luton',
				'Manchester' => 'Manchester',
				'Rochester' => 'Rochester',
				'Milton Keynes' => 'Milton Keynes',
				'Motherwell' => 'Motherwell',
				'North London' => 'North London',
				'Newcastle upon Tyne' => 'Newcastle upon Tyne',
				'Nottingham' => 'Nottingham',
				'Northampton' => 'Northampton',
				'Newport' => 'Newport',
				'Norwich' => 'Norwich',
				'North West London' => 'North West London',
				'Oldham' => 'Oldham',
				'Oxford' => 'Oxford',
				'Paisley' => 'Paisley',
				'Peterborough' => 'Peterborough',
				'Perth' => 'Perth',
				'Plymouth' => 'Plymouth',
				'Portsmouth' => 'Portsmouth',
				'Preston' => 'Preston',
				'Reading' => 'Reading',
				'Redhill' => 'Redhill',
				'Romford' => 'Romford',
				'Sheffield' => 'Sheffield',
				'Swansea' => 'Swansea',
				'South East London' => 'South East London',
				'Stevenage' => 'Stevenage',
				'Stockport' => 'Stockport',
				'Slough' => 'Slough',
				'Sutton' => 'Sutton',
				'Swindon' => 'Swindon',
				'Southampton' => 'Southampton',
				'Salisbury' => 'Salisbury',
				'Sunderland' => 'Sunderland',
				'Southend-on-Sea' => 'Southend-on-Sea',
				'Stoke-on-Trent' => 'Stoke-on-Trent',
				'South West London' => 'South West London',
				'Shrewsbury' => 'Shrewsbury',
				'Taunton' => 'Taunton',
				'Galashiels' => 'Galashiels',
				'Telford' => 'Telford',
				'Tunbridge Wells' => 'Tunbridge Wells',
				'Torquay' => 'Torquay',
				'Truro' => 'Truro',
				'Cleveland' => 'Cleveland',
				'Twickenham' => 'Twickenham',
				'Southall' => 'Southall',
				'West London' => 'West London',
				'Warrington' => 'Warrington',
				'Western Central London' => 'Western Central London',
				'Watford' => 'Watford',
				'Wakefield' => 'Wakefield',
				'Wigan' => 'Wigan',
				'Worcester' => 'Worcester',
				'Walsall' => 'Walsall',
				'Wolverhampton' => 'Wolverhampton',
				'York' => 'York',
				'Lerwick' => 'Lerwick',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
			'return_format' => 'value',
		),
		array (
			'key' => 'field_55d5ffcd8f167',
			'label' => 'Zip',
			'name' => 'zip',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 20,
				'class' => 'field_type-text field_key-field_55d5ffcd8f167',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55d5ffec8f168',
			'label' => 'Phone',
			'name' => 'phone',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-text field_key-field_55d5ffec8f168',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55d600088f169',
			'label' => 'Email',
			'name' => 'email',
			'type' => 'email',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-email field_key-field_55d600088f169',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_582c9902bb744',
			'label' => 'Address',
			'name' => 'company_address',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Address',
			'sub_fields' => array (
				array (
					'key' => 'field_582c9918bb745',
					'label' => 'Address Line 1',
					'name' => 'address_line_1',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_582c993dbb746',
					'label' => 'City',
					'name' => 'city',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_582c997cbb747',
					'label' => 'State',
					'name' => 'state',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => 2,
				),
				array (
					'key' => 'field_582c998fbb748',
					'label' => 'Postal Code (Zip)',
					'name' => 'zip',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array (
			'key' => 'field_582c9a13bb74c',
			'label' => 'Phone',
			'name' => 'company_phone',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Phone',
			'sub_fields' => array (
				array (
					'key' => 'field_582c9a1fbb74d',
					'label' => 'Phone',
					'name' => 'phone',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array (
			'key' => 'field_582c9a30bb74e',
			'label' => 'Email',
			'name' => 'company_email',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Email',
			'sub_fields' => array (
				array (
					'key' => 'field_582c9a3abb74f',
					'label' => 'Email',
					'name' => 'email',
					'type' => 'email',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array (
			'key' => 'field_582c9ad7bb751',
			'label' => 'Social',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_572ce07997d2b',
			'label' => 'FBR Profile Slug',
			'name' => 'fbr_profile',
			'type' => 'text',
			'instructions' => 'Paste only	the company name. Ex: d3solutions out of http://www.fairbusinessreport.org/company/d3solutions/profile',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 70,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_572ce23897d2c',
			'label' => 'Badge Color',
			'name' => 'badge_color',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 30,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'gold' => 'Gold',
				'silver' => 'Silver',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
			'return_format' => 'value',
		),
		array (
			'key' => 'field_55d6007a8f16c',
			'label' => 'Facebook',
			'name' => 'facebook',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-url field_key-field_55d6007a8f16c',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_55d600958f16d',
			'label' => 'Twitter',
			'name' => 'twitter',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-url field_key-field_55d600958f16d',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_55d6009d8f16e',
			'label' => 'Google+',
			'name' => 'google',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-url field_key-field_55d6009d8f16e',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_55d600a98f16f',
			'label' => 'LinkedIn',
			'name' => 'linkedin',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-url field_key-field_55d600a98f16f',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_55d600b28f170',
			'label' => 'Tumblr',
			'name' => 'tumblr',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-url field_key-field_55d600b28f170',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_55d600c08f171',
			'label' => 'Pinterest',
			'name' => 'pinterest',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-url field_key-field_55d600c08f171',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_55d600cc8f172',
			'label' => 'Flickr',
			'name' => 'flickr',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-url field_key-field_55d600cc8f172',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_55f713cfa857d',
			'label' => 'Instagram',
			'name' => 'instagram',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_55d600d78f173',
			'label' => 'Newswire',
			'name' => 'newswire',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-url field_key-field_55d600d78f173',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_564cb1ce59e50',
			'label' => 'Youtube',
			'name' => 'youtube',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_564cb1e059e51',
			'label' => 'Vimeo',
			'name' => 'vimeo',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'company-info',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif; ?>