<?php if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_586d9c293e961',
	'title' => 'Theme Options',
	'fields' => array (
		array (
			'placement' => 'left',
			'endpoint' => 0,
			'key' => 'field_55d4c8ed4b508',
			'label' => 'General',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-tab field_key-field_55d4c8ed4b508',
				'id' => '',
			),
		),
		array (
			'message' => '<h1>General</h1>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586d9b2a2eb7a',
			'label' => 'General',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'return_format' => 'url',
			'preview_size' => 'theme_image_preview',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'key' => 'field_55d4c8814b504',
			'label' => 'Favicon',
			'name' => 'favicon',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-image field_key-field_55d4c8814b504',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_55d4ceba2c1ed',
			'label' => 'Content Background Color',
			'name' => 'content_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d4ceba2c1ed',
				'id' => '',
			),
		),
		array (
			'message' => '<h2>Logo</h2>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586d9b432eb7b',
			'label' => 'Logo',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'return_format' => 'array',
			'preview_size' => 'theme_image_preview',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'key' => 'field_55d4c8aa4b505',
			'label' => 'Logo',
			'name' => 'logo',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-image field_key-field_55d4c8aa4b505',
				'id' => '',
			),
		),
		array (
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'svg',
			'key' => 'field_56f01e04d8ab2',
			'label' => 'SVG Desktop Logo',
			'name' => 'svg_desktop_logo',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-image field_key-field_55d4c8aa4b505',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'key' => 'field_560abb7769cfb',
			'label' => 'Desktop Logo Maximum Width',
			'name' => 'desktop_logo_maximum_width',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'message' => '<h2>Mobile Logo</h2>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586d9b622eb7c',
			'label' => 'Mobile Logo',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'return_format' => 'url',
			'preview_size' => 'theme_image_preview',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'key' => 'field_560abb4369cfa',
			'label' => 'Mobile Logo',
			'name' => 'mobile_logo',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'svg',
			'key' => 'field_56f01e40d8ab3',
			'label' => 'SVG Mobile Logo',
			'name' => 'svg_mobile_logo',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'key' => 'field_560abb9e69cfc',
			'label' => 'Mobile Logo Maximum Width',
			'name' => 'mobile_logo_maximum_width',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'message' => '<h2>Theme Colors</h2>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586d9bb22eb7e',
			'label' => 'Theme Colors',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'sub_fields' => array (
				array (
					'default_value' => '',
					'key' => 'field_560eadf35e138',
					'label' => 'Color',
					'name' => 'color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'key' => 'field_560eaefda8409',
					'label' => 'Color Class Name',
					'name' => 'color_class_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'readonly' => 0,
					'disabled' => 0,
				),
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Theme Color',
			'collapsed' => '',
			'key' => 'field_560eade55e137',
			'label' => 'Theme Colors',
			'name' => 'theme_colors',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'message' => '<h2>Theme Fonts</h2>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586d9b952eb7d',
			'label' => 'Theme Fonts',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 0,
			'message' => '',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'key' => 'field_586d4e91af76d',
			'label' => 'Add Google Fonts?',
			'name' => 'add_google_fonts',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '25',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'placeholder' => '',
			'key' => 'field_586d4f56af76e',
			'label' => 'Google Fonts URL',
			'name' => 'google_fonts_url',
			'type' => 'url',
			'instructions' => 'Go to fonts.google.com and generate your url and paste it here',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_586d4e91af76d',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '75',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 0,
			'message' => '',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'key' => 'field_562e5bcbf0cd5',
			'label' => 'Add typekit fonts?',
			'name' => 'add_typekit_fonts',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '25',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_562e5be0f0cd6',
			'label' => 'Typekit ID',
			'name' => 'typekit_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_562e5bcbf0cd5',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '25',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'sub_fields' => array (
				array (
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'key' => 'field_586d4e4caf76c',
					'label' => 'Display Name',
					'name' => 'display_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'key' => 'field_586d48c9f41f7',
					'label' => 'CSS Name',
					'name' => 'css_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'layout' => 'horizontal',
					'choices' => array (
						'sans' => 'Sans',
						'serif' => 'Serif',
					),
					'default_value' => '',
					'other_choice' => 0,
					'save_other_choice' => 0,
					'allow_null' => 0,
					'return_format' => 'value',
					'key' => 'field_586d48d5f41f8',
					'label' => 'Font Type',
					'name' => 'font_type',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Font',
			'collapsed' => '',
			'key' => 'field_5602e62ed6d6a',
			'label' => 'Theme Fonts',
			'name' => 'theme_fonts',
			'type' => 'repeater',
			'instructions' => 'Add fonts to the theme',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '100',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'left',
			'endpoint' => 0,
			'key' => 'field_55d4c8be4b506',
			'label' => 'Header',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-tab field_key-field_55d4c8be4b506',
				'id' => '',
			),
		),
		array (
			'message' => '<h1>Header</h1>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586d9774d42ef',
			'label' => 'Header',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'Top Menu' => 'Top Menu',
				'Left Side Menu' => 'Left Side Menu',
				'Right Side Menu' => 'Right Side Menu',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_560ec99f29270',
			'label' => 'Header Type',
			'name' => 'header_type',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'header-no-overlap' => 'Site header does not overlap page header',
				'header-overlap' => 'Site header overlaps page header',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_572279229a959',
			'label' => 'Site Header Position',
			'name' => 'top_header_position',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 0,
			'message' => 'Will open with a button',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'key' => 'field_560433b34ef11',
			'label' => 'Hide menu on desktop?',
			'name' => 'hide_menu_on_desktop',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 0,
			'message' => '',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'key' => 'field_5604338a4ef10',
			'label' => 'Is header in grid?',
			'name' => 'is_header_in_grid',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_55d4c8cd4b507',
			'label' => 'Header Background Color',
			'name' => 'header_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d4c8cd4b507',
				'id' => '',
			),
		),
		array (
			'default_value' => 1,
			'min' => 0,
			'max' => 1,
			'step' => '0.05',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_55e870ab71ed8',
			'label' => 'Header Background Opacity',
			'name' => 'header_background_opacity',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-number field_key-field_55e870ab71ed8',
				'id' => '',
			),
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'key' => 'field_55f30b4e7e257',
			'label' => 'Header Height',
			'name' => 'desktop_header_height',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-number field_key-field_55f30b4e7e257',
				'id' => '',
			),
		),
		array (
			'message' => '<h2>Header Widget Bar Styles</h2>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586ee507542cd',
			'label' => 'Header Widget Bar Styles',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_586ee52f542ce',
			'label' => 'Header Widget Background Color',
			'name' => 'header_widget_bg_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d4c8cd4b507',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_586ee54d542cf',
			'label' => 'Header Widget Text Color',
			'name' => 'header_widget_txt_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d4c8cd4b507',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_586ee55a542d0',
			'label' => 'Header Widget Link Color',
			'name' => 'header_widget_link_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d4c8cd4b507',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_586ee56d542d1',
			'label' => 'Header Widget Link Hover Color',
			'name' => 'header_widget_link_hover_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d4c8cd4b507',
				'id' => '',
			),
		),
		array (
			'message' => '<h2>Top Menu Styles</h2>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586d9798d42f0',
			'label' => 'Top Menu Styles',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560ec99f29270',
						'operator' => '==',
						'value' => 'Top Menu',
					),
				),
			),
			'wrapper' => array (
				'width' => '100',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 1,
			'message' => '',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'key' => 'field_56f01ecbd8ab4',
			'label' => 'Use Sticky Header?',
			'name' => 'sticky_header',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560ec99f29270',
						'operator' => '==',
						'value' => 'Top Menu',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-number field_key-field_55f30b4e7e257',
				'id' => '',
			),
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'left' => 'left',
				'center' => 'center',
				'right' => 'right',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_5605b94321d7d',
			'label' => 'Logo Position',
			'name' => 'logo_position',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560ec99f29270',
						'operator' => '==',
						'value' => 'Top Menu',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'top' => 'Centered above menu',
				'divided' => 'In between two menus',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_5640cb7f7749f',
			'label' => 'Center Logo Menu Type',
			'name' => 'center_logo_menu_type',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5605b94321d7d',
						'operator' => '==',
						'value' => 'center',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'key' => 'field_5640d20d9edeb',
			'label' => 'Logo Height',
			'name' => 'logo_height',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560ec99f29270',
						'operator' => '==',
						'value' => 'Top Menu',
					),
					array (
						'field' => 'field_5605b94321d7d',
						'operator' => '==',
						'value' => 'center',
					),
					array (
						'field' => 'field_5640cb7f7749f',
						'operator' => '==',
						'value' => 'top',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'message' => '<h2>Sticky Header Styles</h2>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586d97bad42f1',
			'label' => 'Sticky Header Styles',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '100',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 50,
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'key' => 'field_56f01fa1d8ab6',
			'label' => 'Sticky Header Height',
			'name' => 'sticky_header_height',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56f01ecbd8ab4',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '100',
				'class' => 'field_type-number field_key-field_55f30b4e7e257',
				'id' => '',
			),
		),
		array (
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
			'key' => 'field_5796639eb9e7b',
			'label' => 'Sticky Header Logo',
			'name' => 'dark_sticky_logo',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56f01ecbd8ab4',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-number field_key-field_55f30b4e7e257',
				'id' => '',
			),
		),
		array (
			'default_value' => '#FFFFFF',
			'key' => 'field_586d4752f41f1',
			'label' => 'Sticky Header Background Color',
			'name' => 'dark_sticky_bg',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56f01ecbd8ab4',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '#FFFFFF',
			'key' => 'field_586d47b7f41f3',
			'label' => 'Sticky Header Link Color',
			'name' => 'dark_sticky_link',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56f01ecbd8ab4',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '#FFFFFF',
			'key' => 'field_586d47cff41f4',
			'label' => 'Sticky Header Link Hover Color',
			'name' => 'dark_sticky_link_hover',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56f01ecbd8ab4',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'message' => '<h2>Menu Styles</h2>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586d9948b94b2',
			'label' => 'Menu Styles',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '100',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_586da5a7c613d',
			'label' => 'Menu Dropdown Background Color',
			'name' => 'menu_dropdown_bg_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_55d4c9004b509',
			'label' => 'Menu Link Color',
			'name' => 'menu_link_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d4c9004b509',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_55d4ccd62c1e6',
			'label' => 'Menu Link Active Color',
			'name' => 'menu_link_active_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d4ccd62c1e6',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => 12,
			'max' => 50,
			'step' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_55d4c9204b50a',
			'label' => 'Menu Font Size',
			'name' => 'menu_font_size',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-number field_key-field_55d4c9204b50a',
				'id' => '',
			),
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'key' => 'field_5665e5b63c1ee',
			'label' => 'Menu Line Height',
			'name' => 'menu_line_height',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-number field_key-field_55d4c9204b50a',
				'id' => '',
			),
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'\'Bree Serif\', serif' => 'Bree Serif',
				'\'Roboto\', sans' => 'Roboto',
				'\'museo-sans\', sans' => 'Museo Sans',
			),
			'default_value' => array (
			),
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_5602e24562fc3',
			'label' => 'Menu Font Family',
			'name' => 'menu_font_family',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'message' => '<h2>Mobile Styles</h2>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586d909df33f8',
			'label' => 'Mobile Styles',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '100',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'key' => 'field_5604357499149',
			'label' => 'Mobile Header Height',
			'name' => 'mobile_header_height',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-number field_key-field_55f30b4e7e257',
				'id' => '',
			),
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'default_value' => '#FFFFFF',
			'key' => 'field_5665e7433c1ef',
			'label' => 'Mobile Menu Item Divider Color',
			'name' => 'mobile_menu_item_divider_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560ec99f29270',
						'operator' => '==',
						'value' => 'Top Menu',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '#FFFFFF',
			'key' => 'field_5665e4d43c1ea',
			'label' => 'Menu Icon Color',
			'name' => 'menu_icon_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '#FFFFFF',
			'key' => 'field_5665e5293c1ec',
			'label' => 'Active Menu Icon Color',
			'name' => 'active_menu_icon_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_560eca6029271',
			'label' => 'Mobile Menu Dropdown Background Color',
			'name' => 'mobile_menu_bg_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560ec99f29270',
						'operator' => '==',
						'value' => 'Top Menu',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_586d8fb0f33f3',
			'label' => 'Mobile Menu Link Color',
			'name' => 'mobile_menu_link_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560ec99f29270',
						'operator' => '==',
						'value' => 'Top Menu',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d4c9004b509',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_586d8fc4f33f4',
			'label' => 'Mobile Link Active Color',
			'name' => 'mobile_menu_link_active_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560ec99f29270',
						'operator' => '==',
						'value' => 'Top Menu',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d4ccd62c1e6',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => 12,
			'max' => 50,
			'step' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_586d8fd4f33f5',
			'label' => 'Mobile Menu Font Size',
			'name' => 'mobile_menu_font_size',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560ec99f29270',
						'operator' => '==',
						'value' => 'Top Menu',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-number field_key-field_55d4c9204b50a',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'key' => 'field_586d8fe9f33f6',
			'label' => 'Mobile Menu Line Height',
			'name' => 'mobile_menu_line_height',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560ec99f29270',
						'operator' => '==',
						'value' => 'Top Menu',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-number field_key-field_55d4c9204b50a',
				'id' => '',
			),
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'\'Bree Serif\', serif' => 'Bree Serif',
				'\'Roboto\', sans' => 'Roboto',
				'\'museo-sans\', sans' => 'Museo Sans',
			),
			'default_value' => array (
			),
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_586d9065f33f7',
			'label' => 'Mobile Menu Font Family',
			'name' => 'mobile_menu_font_family',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560ec99f29270',
						'operator' => '==',
						'value' => 'Top Menu',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'left',
			'endpoint' => 0,
			'key' => 'field_55d616e76456c',
			'label' => 'Footer',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-tab field_key-field_55d616e76456c',
				'id' => '',
			),
		),
		array (
			'message' => '<h1>Footer</h1>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586d96fbd42ec',
			'label' => 'Footer',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
			'key' => 'field_5718ff8fcd62e',
			'label' => 'Footer Logo',
			'name' => 'footer_logo',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55e4a26c89205',
				'id' => '',
			),
		),
		array (
			'message' => '<h2>Top Footer</h2>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586d9728d42ed',
			'label' => 'Top Footer',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_55d617006456d',
			'label' => 'Footer Top Background Color',
			'name' => 'footer_top_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d617006456d',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_55d617196456e',
			'label' => 'Footer Top Text Color',
			'name' => 'footer_top_text_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d617196456e',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_55d6172c6456f',
			'label' => 'Footer Top Link Color',
			'name' => 'footer_top_link_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d6172c6456f',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_55d6173a64570',
			'label' => 'Footer Top Link Hover Color',
			'name' => 'footer_top_link_hover_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d6173a64570',
				'id' => '',
			),
		),
		array (
			'message' => '<h2>Bottom Footer</h2>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586d973bd42ee',
			'label' => 'Bottom Footer',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_55e4a26589202',
			'label' => 'Footer Bottom Background Color',
			'name' => 'footer_bottom_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55e4a26589202',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_55e4a26989203',
			'label' => 'Footer Bottom Text Color',
			'name' => 'footer_bottom_text_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55e4a26989203',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_55e4a26a89204',
			'label' => 'Footer Bottom Link Color',
			'name' => 'footer_bottom_link_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55e4a26a89204',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_55e4a26c89205',
			'label' => 'Footer Bottom Link Hover Color',
			'name' => 'footer_bottom_link_hover_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55e4a26c89205',
				'id' => '',
			),
		),
		array (
			'placement' => 'left',
			'endpoint' => 0,
			'key' => 'field_56043ca610408',
			'label' => 'Typography',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'message' => '<h1>Typography</h1>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586d96d6d42eb',
			'label' => 'Typography',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_55e9e8c340c74',
			'label' => 'Text Highlight Color',
			'name' => 'text_highlight_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55e9e8c340c74',
				'id' => '',
			),
		),
		array (
			'default_value' => '#000000',
			'key' => 'field_55e4b1fd06820',
			'label' => 'Default Font Color',
			'name' => 'main_font_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55e4b1fd06820',
				'id' => '',
			),
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'\'Bree Serif\', serif' => 'Bree Serif',
				'\'Roboto\', sans' => 'Roboto',
				'\'museo-sans\', sans' => 'Museo Sans',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_560f06f06f1ba',
			'label' => 'Default Font Family',
			'name' => 'default_font_family',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'message' => '<h2>Headings Default Styles</h2>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586d95d3dc65a',
			'label' => 'Headings Default Styles',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'\'Bree Serif\', serif' => 'Bree Serif',
				'\'Roboto\', sans' => 'Roboto',
				'\'museo-sans\', sans' => 'Museo Sans',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_56043cbf10409',
			'label' => 'Headings Font Family',
			'name' => 'headings_font_family',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'default_value' => '',
			'key' => 'field_56043cd61040a',
			'label' => 'Headings Font Color',
			'name' => 'headings_font_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'multiple' => 0,
			'allow_null' => 1,
			'choices' => array (
				'none' => 'none',
				'uppercase' => 'uppercase',
				'lowercase' => 'lowercase',
				'capitalize' => 'capitalize',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_56043cf61040b',
			'label' => 'Headings Text Transform',
			'name' => 'headings_text_transform',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'default_value' => '',
			'min' => '0.8',
			'max' => 2,
			'step' => '0.05',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_56043d281040c',
			'label' => 'Headings Line Height',
			'name' => 'headings_line_height',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				400 => '400',
				100 => '100',
				300 => '300',
				500 => '500',
				600 => '600',
				700 => '700',
				800 => '800',
				900 => '900',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_56043d461040d',
			'label' => 'Headings Font Weight',
			'name' => 'headings_font_weight',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'message' => '<h2>Paragraph Default Styles</h2>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586d95e9dc65b',
			'label' => 'Paragraph Default Styles',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'\'Bree Serif\', serif' => 'Bree Serif',
				'\'Roboto\', sans' => 'Roboto',
				'\'museo-sans\', sans' => 'Museo Sans',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_56043d901040e',
			'label' => 'Paragraph Font Family',
			'name' => 'paragraph_font_family',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'default_value' => '#000000',
			'key' => 'field_56043dab1040f',
			'label' => 'Paragraph Font Color',
			'name' => 'paragraph_font_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'none' => 'none',
				'uppercase' => 'uppercase',
				'lowercase' => 'lowercase',
				'capitalize' => 'capitalize',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_56043dc610410',
			'label' => 'Paragraph Text Transform',
			'name' => 'paragraph_text_transform',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'default_value' => 1,
			'min' => '0.5',
			'max' => 2,
			'step' => '0.05',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_56043dda10411',
			'label' => 'Paragraph Line Height',
			'name' => 'paragraph_line_height',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				400 => '400',
				100 => '100',
				300 => '300',
				500 => '500',
				600 => '600',
				700 => '700',
				800 => '800',
				900 => '900',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_56043e0610413',
			'label' => 'Paragraph Font Weight',
			'name' => 'paragraph_font_weight',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'default_value' => '',
			'key' => 'field_5626690ae235d',
			'label' => 'Link Text Color',
			'name' => 'link_text_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_5626691de235e',
			'label' => 'Link Text Hover Color',
			'name' => 'link_text_hover_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'left',
			'endpoint' => 0,
			'key' => 'field_5638f0365f870',
			'label' => 'Blog',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'message' => '<h1>Blog Settings</h1>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586d96b0d42ea',
			'label' => 'Blog Settings',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				1 => '1',
				2 => '2',
				3 => '3',
			),
			'default_value' => array (
				0 => 1,
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_586d9690d42e9',
			'label' => 'Blog Post Layout',
			'name' => 'blog_post_layout',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'standard' => 'Standard Grid',
				'masonry' => 'Masonry Grid',
				'carousel' => 'Carousel',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_58a3bbb521143',
			'label' => 'Blog Grid Type',
			'name' => 'blog_type',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 30,
			'min' => 10,
			'max' => '',
			'step' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_5638f04c5f871',
			'label' => 'Excerpt Length',
			'name' => 'excerpt_length',
			'type' => 'number',
			'instructions' => 'How many words do you want the post excerpts to display?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 1,
			'message' => 'Check this if you want to finish the sentence of the excerpt (No weird cuts).',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'key' => 'field_5638f0b75f872',
			'label' => 'Finish sentence',
			'name' => 'finish_sentence',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58a3be00d2f88',
			'label' => 'Custom Blog Feed Class',
			'name' => 'custom_blog_class',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 1,
			'min' => 1,
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58a3bbe121144',
			'label' => 'Columns On Mobile',
			'name' => 'columns_on_mobile',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '33',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 2,
			'min' => 1,
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58a3bc0021145',
			'label' => 'Columns On Tablet',
			'name' => 'columns_on_tablet',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '33',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 3,
			'min' => 1,
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_58a3bc0e21146',
			'label' => 'Columns On Desktop',
			'name' => 'columns_on_desktop',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '33',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'key' => 'field_58a3bc3521147',
			'label' => 'Gutters on Mobile',
			'name' => 'gutters_on_mobile',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '33',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'key' => 'field_58a3bc5b21148',
			'label' => 'Gutters on Tablet',
			'name' => 'gutters_on_tablet',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '33',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'key' => 'field_58a3bc6821149',
			'label' => 'Gutters on Desktop',
			'name' => 'gutters_on_desktop',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '33',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'message' => '<h2>Blog Section Animation</h2>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586ed8ec7ccea',
			'label' => 'Blog Section Animation',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 0,
			'message' => '',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'key' => 'field_586ed9127cceb',
			'label' => 'Animate Blog Section?',
			'name' => 'animate_blog_section',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'bounce' => 'Bounce',
				'flash' => 'Flash',
				'pulse' => 'Pulse',
				'rubberBand' => 'Rubber Band',
				'shake' => 'Shake',
				'swing' => 'Swing',
				'tada' => 'Ta Da',
				'wobble' => 'Wobble',
				'jello' => 'Jello',
				'bounceIn' => 'Bounce In',
				'bounceInDown' => 'Bounce In Down',
				'bounceInLeft' => 'Bounce In Left',
				'bounceInRight' => 'Bounce In Right',
				'bounceInUp' => 'Bounce In Up',
				'bounceOut' => 'Bounce Out',
				'bounceOutDown' => 'Bounce Out Down',
				'bounceOutLeft' => 'Bounce Out Left',
				'bounceOutRight' => 'Bounce Out Right',
				'bounceOutUp' => 'Bounce Out Up',
				'fadeIn' => 'Fade In',
				'fadeInDown' => 'Fade In Down',
				'fadeInDownBig' => 'Fade In Down Big',
				'fadeInLeft' => 'Fade In Left',
				'fadeInLeftBig' => 'Fade In Left Big',
				'fadeInRight' => 'Fade In Right',
				'fadeInRightBig' => 'Fade In Right Big',
				'fadeInUp' => 'Fade In Up',
				'fadeInUpBig' => 'Fade In Up Big',
				'fadeOut' => 'Fade Out',
				'fadeOutDown' => 'Fade Out Down',
				'fadeOutDownBig' => 'Fade Out Down Big',
				'fadeOutLeft' => 'Fade Out Left',
				'fadeOutLeftBig' => 'Fade Out Left Big',
				'fadeOutRight' => 'Fade Out Right',
				'fadeOutRightBig' => 'Fade Out Right Big',
				'fadeOutUp' => 'Fade Out Up',
				'fadeOutUpBig' => 'Fade Out Up Big',
				'flipInX' => 'Flip In X Axis',
				'flipInY' => 'Flip In Y Axis',
				'flipOutX' => 'Flip Out X Axis',
				'flipOutY' => 'Flip Out Y Axis',
				'lightSpeedIn' => 'Light Speed In',
				'lightSpeedOut' => 'Light Speed Out',
				'rotateIn' => 'Rotate In',
				'rotateInDownLeft' => 'Rotate In Down Left',
				'rotateInDownRight' => 'Rotate In Down Right',
				'rotateInUpLeft' => 'Rotate In Up Left',
				'rotateInUpRight' => 'Rotate In Up Right',
				'rotateOut' => 'Rotate Out',
				'rotateOutDownLeft' => 'Rotate Out Down Left',
				'rotateOutDownRight' => 'Rotate Out Down Right',
				'rotateOutUpLeft' => 'Rotate Out Up Left',
				'rotateOutUpRight' => 'Rotate Out Up Right',
				'hinge' => 'Hinge',
				'rollIn' => 'Roll In',
				'rollOut' => 'Roll Out',
				'zoomIn' => 'Zoom In',
				'zoomInDown' => 'Zoom In Down',
				'zoomInLeft' => 'Zoom In Left',
				'zoomInRight' => 'Zoom In Right',
				'zoomInUp' => 'Zoom In Up',
				'zoomOut' => 'Zoom Out',
				'zoomOutDown' => 'Zoom Out Down',
				'zoomOutLeft' => 'Zoom Out Left',
				'zoomOutRight' => 'Zoom Out Right',
				'zoomOutUp' => 'Zoom Out Up',
				'slideInDown' => 'Slide In Down',
				'slideInLeft' => 'Slide In Left',
				'slideInRight' => 'Slide In Right',
				'slideInUp' => 'Slide In Up',
				'slideOutDown' => 'Slide Out Down',
				'slideOutLeft' => 'Slide Out Left',
				'slideOutRight' => 'Slide Out Right',
				'slideOutUp' => 'Slide Out Up',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_586ed9297ccec',
			'label' => 'Blog Animation Effect',
			'name' => 'blog_animation_effect',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_586ed9127cceb',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => 0,
			'max' => '',
			'step' => '0.01',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'seconds',
			'key' => 'field_586ed9657cced',
			'label' => 'Blog Animation Delay',
			'name' => 'blog_animation_delay',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_586ed9127cceb',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'pixels',
			'key' => 'field_586ed9997ccee',
			'label' => 'Blog Animation Offset',
			'name' => 'blog_animation_offset',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_586ed9127cceb',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'message' => '<h2>Blog Pagination Styles</h2>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586d9568739f4',
			'label' => 'Blog Pagination Styles',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '#CCCCCC',
			'key' => 'field_5638f1485f875',
			'label' => 'Pagination Item Background Color',
			'name' => 'pagination_item_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '#000000',
			'key' => 'field_5638f17d5f876',
			'label' => 'Pagination Item Text Color',
			'name' => 'pagination_item_text_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '#000000',
			'key' => 'field_5638f0e75f873',
			'label' => 'Pagination Current Item Background Color',
			'name' => 'pagination_current_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '#FFFFFF',
			'key' => 'field_5638f1295f874',
			'label' => 'Pagination Current Item Text Color',
			'name' => 'pagination_current_text_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'message' => '<h2>Single Post Options</h2>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_588a3e7ac0fab',
			'label' => 'Single Post Options',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 0,
			'message' => 'Do you want to use the news page header for your single post page (instead of the post image)?',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'key' => 'field_588a3e06b2de0',
			'label' => 'Use News Page Header for Single Post',
			'name' => 'news_header',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 0,
			'message' => 'Do you want to hide the news page header content for your single post page?',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'key' => 'field_588a3eacc0fac',
			'label' => 'Hide News Page Title',
			'name' => 'news_title',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'icon1' => 'Icon with no background',
				'icon2' => 'Icon with square background',
				'icon3' => 'Icon with circle background',
				'icon4' => 'Icon with rounded square background',
				'icon5' => 'Outline only icon with circle background outline',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_589b8ddce1f85',
			'label' => 'Social Share Icon Type',
			'name' => 'social_share_icon_type',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'left',
			'endpoint' => 0,
			'key' => 'field_564a234a7b6c1',
			'label' => 'Extras',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'message' => '<h1>Extras</h1>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586d9acb2eb78',
			'label' => 'Extras',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_573e0c3993926',
			'label' => 'Copyright Text',
			'name' => 'copyright_text',
			'type' => 'text',
			'instructions' => 'Use instead of default copyright txt ( [company name] © [current year] ). Will still add copyright symbol and current year at the end',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 100,
				'class' => '',
				'id' => '',
			),
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'message' => '',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586d9ae32eb79',
			'label' => 'Hover Box Settings',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'key' => 'field_564a25ae7b6cd',
			'label' => 'Sadie Effect Gradient Top Color',
			'name' => 'sadie_effect_gradient_top_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 1,
			'min' => 0,
			'max' => 1,
			'step' => '0.01',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_564a25f37b6cf',
			'label' => 'Sadie Effect Gradient Top Color Opacity',
			'name' => 'sadie_effect_gradient_top_color_opacity',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'default_value' => '',
			'key' => 'field_564a258b7b6cc',
			'label' => 'Sadie Effect Gradient Bottom Color',
			'name' => 'sadie_effect_gradient_bottom_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 1,
			'min' => 0,
			'max' => 1,
			'step' => '0.01',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_564a25ce7b6ce',
			'label' => 'Sadie Effect Gradient Bottom Color Opacity',
			'name' => 'sadie_effect_gradient_bottom_color_opacity',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'message' => '<h2>404 Settings</h2>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_586d9bf92eb7f',
			'label' => '404 Settings',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'return_format' => 'url',
			'preview_size' => 'theme_image_preview',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'key' => 'field_56265e29e9709',
			'label' => '404 Header Image',
			'name' => '404_header_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-general-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif; ?>