<?php if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_5722715c2103e',
	'title' => 'Theme Options',
	'fields' => array (
		array (
			'key' => 'field_55d4c8ed4b508',
			'label' => 'General',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-tab field_key-field_55d4c8ed4b508',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_55d4c8814b504',
			'label' => 'Favicon',
			'name' => 'favicon',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-image field_key-field_55d4c8814b504',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'theme_image_preview',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_55d4c8aa4b505',
			'label' => 'Logo',
			'name' => 'logo',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-image field_key-field_55d4c8aa4b505',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'theme_image_preview',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_56f01e04d8ab2',
			'label' => 'SVG Desktop Logo',
			'name' => 'svg_desktop_logo',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-image field_key-field_55d4c8aa4b505',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'svg',
		),
		array (
			'key' => 'field_560abb4369cfa',
			'label' => 'Mobile Logo',
			'name' => 'mobile_logo',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'theme_image_preview',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_56f01e40d8ab3',
			'label' => 'SVG Mobile Logo',
			'name' => 'svg_mobile_logo',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'svg',
		),
		array (
			'key' => 'field_560abb7769cfb',
			'label' => 'Desktop Logo Maximum Width',
			'name' => 'desktop_logo_maximum_width',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_560abb9e69cfc',
			'label' => 'Mobile Logo Maximum Width',
			'name' => 'mobile_logo_maximum_width',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55d4ceba2c1ed',
			'label' => 'Content Background Color',
			'name' => 'content_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d4ceba2c1ed',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_55e4b1fd06820',
			'label' => 'Main Font Color',
			'name' => 'main_font_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55e4b1fd06820',
				'id' => '',
			),
			'default_value' => '#000000',
		),
		array (
			'key' => 'field_55e9e8c340c74',
			'label' => 'Text Highlight Color',
			'name' => 'text_highlight_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55e9e8c340c74',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_560eade55e137',
			'label' => 'Theme Colors',
			'name' => 'theme_colors',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add Theme Color',
			'sub_fields' => array (
				array (
					'key' => 'field_560eadf35e138',
					'label' => 'Color',
					'name' => 'color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array (
					'key' => 'field_560eaefda8409',
					'label' => 'Color Class Name',
					'name' => 'color_class_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_5602e62ed6d6a',
			'label' => 'Theme Fonts',
			'name' => 'theme_fonts',
			'type' => 'repeater',
			'instructions' => 'Add fonts to the theme',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add Font',
			'sub_fields' => array (
				array (
					'key' => 'field_5602e644d6d6b',
					'label' => 'Font',
					'name' => 'theme_font',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 67,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'ABeeZee' => 'ABeeZee',
						'Abel' => 'Abel',
						'Abril Fatface' => 'Abril Fatface',
						'Aclonica' => 'Aclonica',
						'Acme' => 'Acme',
						'Actor' => 'Actor',
						'Adamina' => 'Adamina',
						'Advent Pro' => 'Advent Pro',
						'Aguafina Script' => 'Aguafina Script',
						'Akronim' => 'Akronim',
						'Aladin' => 'Aladin',
						'Aldrich' => 'Aldrich',
						'Alef' => 'Alef',
						'Alegreya' => 'Alegreya',
						'Alegreya SC' => 'Alegreya SC',
						'Alegreya Sans' => 'Alegreya Sans',
						'Alegreya Sans SC' => 'Alegreya Sans SC',
						'Alex Brush' => 'Alex Brush',
						'Alfa Slab One' => 'Alfa Slab One',
						'Alice' => 'Alice',
						'Alike' => 'Alike',
						'Alike Angular' => 'Alike Angular',
						'Allan' => 'Allan',
						'Allerta' => 'Allerta',
						'Allerta Stencil' => 'Allerta Stencil',
						'Allura' => 'Allura',
						'Almendra' => 'Almendra',
						'Almendra Display' => 'Almendra Display',
						'Almendra SC' => 'Almendra SC',
						'Amarante' => 'Amarante',
						'Amaranth' => 'Amaranth',
						'Amatic SC' => 'Amatic SC',
						'Amethysta' => 'Amethysta',
						'Amiri' => 'Amiri',
						'Amita' => 'Amita',
						'Anaheim' => 'Anaheim',
						'Andada' => 'Andada',
						'Andika' => 'Andika',
						'Angkor' => 'Angkor',
						'Annie Use Your Telescope' => 'Annie Use Your Telescope',
						'Anonymous Pro' => 'Anonymous Pro',
						'Antic' => 'Antic',
						'Antic Didone' => 'Antic Didone',
						'Antic Slab' => 'Antic Slab',
						'Anton' => 'Anton',
						'Arapey' => 'Arapey',
						'Arbutus' => 'Arbutus',
						'Arbutus Slab' => 'Arbutus Slab',
						'Architects Daughter' => 'Architects Daughter',
						'Archivo Black' => 'Archivo Black',
						'Archivo Narrow' => 'Archivo Narrow',
						'Arimo' => 'Arimo',
						'Arizonia' => 'Arizonia',
						'Armata' => 'Armata',
						'Artifika' => 'Artifika',
						'Arvo' => 'Arvo',
						'Arya' => 'Arya',
						'Asap' => 'Asap',
						'Asar' => 'Asar',
						'Asset' => 'Asset',
						'Astloch' => 'Astloch',
						'Asul' => 'Asul',
						'Atomic Age' => 'Atomic Age',
						'Aubrey' => 'Aubrey',
						'Audiowide' => 'Audiowide',
						'Autour One' => 'Autour One',
						'Average' => 'Average',
						'Average Sans' => 'Average Sans',
						'Averia Gruesa Libre' => 'Averia Gruesa Libre',
						'Averia Libre' => 'Averia Libre',
						'Averia Sans Libre' => 'Averia Sans Libre',
						'Averia Serif Libre' => 'Averia Serif Libre',
						'Bad Script' => 'Bad Script',
						'Balthazar' => 'Balthazar',
						'Bangers' => 'Bangers',
						'Basic' => 'Basic',
						'Battambang' => 'Battambang',
						'Baumans' => 'Baumans',
						'Bayon' => 'Bayon',
						'Belgrano' => 'Belgrano',
						'Belleza' => 'Belleza',
						'BenchNine' => 'BenchNine',
						'Bentham' => 'Bentham',
						'Berkshire Swash' => 'Berkshire Swash',
						'Bevan' => 'Bevan',
						'Bigelow Rules' => 'Bigelow Rules',
						'Bigshot One' => 'Bigshot One',
						'Bilbo' => 'Bilbo',
						'Bilbo Swash Caps' => 'Bilbo Swash Caps',
						'Biryani' => 'Biryani',
						'Bitter' => 'Bitter',
						'Black Ops One' => 'Black Ops One',
						'Bokor' => 'Bokor',
						'Bonbon' => 'Bonbon',
						'Boogaloo' => 'Boogaloo',
						'Bowlby One' => 'Bowlby One',
						'Bowlby One SC' => 'Bowlby One SC',
						'Brawler' => 'Brawler',
						'Bree Serif' => 'Bree Serif',
						'Bubblegum Sans' => 'Bubblegum Sans',
						'Bubbler One' => 'Bubbler One',
						'Buda' => 'Buda',
						'Buenard' => 'Buenard',
						'Butcherman' => 'Butcherman',
						'Butterfly Kids' => 'Butterfly Kids',
						'Cabin' => 'Cabin',
						'Cabin Condensed' => 'Cabin Condensed',
						'Cabin Sketch' => 'Cabin Sketch',
						'Caesar Dressing' => 'Caesar Dressing',
						'Cagliostro' => 'Cagliostro',
						'Calligraffitti' => 'Calligraffitti',
						'Cambay' => 'Cambay',
						'Cambo' => 'Cambo',
						'Candal' => 'Candal',
						'Cantarell' => 'Cantarell',
						'Cantata One' => 'Cantata One',
						'Cantora One' => 'Cantora One',
						'Capriola' => 'Capriola',
						'Cardo' => 'Cardo',
						'Carme' => 'Carme',
						'Carrois Gothic' => 'Carrois Gothic',
						'Carrois Gothic SC' => 'Carrois Gothic SC',
						'Carter One' => 'Carter One',
						'Catamaran' => 'Catamaran',
						'Caudex' => 'Caudex',
						'Caveat' => 'Caveat',
						'Caveat Brush' => 'Caveat Brush',
						'Cedarville Cursive' => 'Cedarville Cursive',
						'Ceviche One' => 'Ceviche One',
						'Changa One' => 'Changa One',
						'Chango' => 'Chango',
						'Chau Philomene One' => 'Chau Philomene One',
						'Chela One' => 'Chela One',
						'Chelsea Market' => 'Chelsea Market',
						'Chenla' => 'Chenla',
						'Cherry Cream Soda' => 'Cherry Cream Soda',
						'Cherry Swash' => 'Cherry Swash',
						'Chewy' => 'Chewy',
						'Chicle' => 'Chicle',
						'Chivo' => 'Chivo',
						'Chonburi' => 'Chonburi',
						'Cinzel' => 'Cinzel',
						'Cinzel Decorative' => 'Cinzel Decorative',
						'Clicker Script' => 'Clicker Script',
						'Coda' => 'Coda',
						'Coda Caption' => 'Coda Caption',
						'Codystar' => 'Codystar',
						'Combo' => 'Combo',
						'Comfortaa' => 'Comfortaa',
						'Coming Soon' => 'Coming Soon',
						'Concert One' => 'Concert One',
						'Condiment' => 'Condiment',
						'Content' => 'Content',
						'Contrail One' => 'Contrail One',
						'Convergence' => 'Convergence',
						'Cookie' => 'Cookie',
						'Copse' => 'Copse',
						'Corben' => 'Corben',
						'Courgette' => 'Courgette',
						'Cousine' => 'Cousine',
						'Coustard' => 'Coustard',
						'Covered By Your Grace' => 'Covered By Your Grace',
						'Crafty Girls' => 'Crafty Girls',
						'Creepster' => 'Creepster',
						'Crete Round' => 'Crete Round',
						'Crimson Text' => 'Crimson Text',
						'Croissant One' => 'Croissant One',
						'Crushed' => 'Crushed',
						'Cuprum' => 'Cuprum',
						'Cutive' => 'Cutive',
						'Cutive Mono' => 'Cutive Mono',
						'Damion' => 'Damion',
						'Dancing Script' => 'Dancing Script',
						'Dangrek' => 'Dangrek',
						'Dawning of a New Day' => 'Dawning of a New Day',
						'Days One' => 'Days One',
						'Dekko' => 'Dekko',
						'Delius' => 'Delius',
						'Delius Swash Caps' => 'Delius Swash Caps',
						'Delius Unicase' => 'Delius Unicase',
						'Della Respira' => 'Della Respira',
						'Denk One' => 'Denk One',
						'Devonshire' => 'Devonshire',
						'Dhurjati' => 'Dhurjati',
						'Didact Gothic' => 'Didact Gothic',
						'Diplomata' => 'Diplomata',
						'Diplomata SC' => 'Diplomata SC',
						'Domine' => 'Domine',
						'Donegal One' => 'Donegal One',
						'Doppio One' => 'Doppio One',
						'Dorsa' => 'Dorsa',
						'Dosis' => 'Dosis',
						'Dr Sugiyama' => 'Dr Sugiyama',
						'Droid Sans' => 'Droid Sans',
						'Droid Sans Mono' => 'Droid Sans Mono',
						'Droid Serif' => 'Droid Serif',
						'Duru Sans' => 'Duru Sans',
						'Dynalight' => 'Dynalight',
						'EB Garamond' => 'EB Garamond',
						'Eagle Lake' => 'Eagle Lake',
						'Eater' => 'Eater',
						'Economica' => 'Economica',
						'Eczar' => 'Eczar',
						'Ek Mukta' => 'Ek Mukta',
						'Electrolize' => 'Electrolize',
						'Elsie' => 'Elsie',
						'Elsie Swash Caps' => 'Elsie Swash Caps',
						'Emblema One' => 'Emblema One',
						'Emilys Candy' => 'Emilys Candy',
						'Engagement' => 'Engagement',
						'Englebert' => 'Englebert',
						'Enriqueta' => 'Enriqueta',
						'Erica One' => 'Erica One',
						'Esteban' => 'Esteban',
						'Euphoria Script' => 'Euphoria Script',
						'Ewert' => 'Ewert',
						'Exo' => 'Exo',
						'Exo 2' => 'Exo 2',
						'Expletus Sans' => 'Expletus Sans',
						'Fanwood Text' => 'Fanwood Text',
						'Fascinate' => 'Fascinate',
						'Fascinate Inline' => 'Fascinate Inline',
						'Faster One' => 'Faster One',
						'Fasthand' => 'Fasthand',
						'Fauna One' => 'Fauna One',
						'Federant' => 'Federant',
						'Federo' => 'Federo',
						'Felipa' => 'Felipa',
						'Fenix' => 'Fenix',
						'Finger Paint' => 'Finger Paint',
						'Fira Mono' => 'Fira Mono',
						'Fira Sans' => 'Fira Sans',
						'Fjalla One' => 'Fjalla One',
						'Fjord One' => 'Fjord One',
						'Flamenco' => 'Flamenco',
						'Flavors' => 'Flavors',
						'Fondamento' => 'Fondamento',
						'Fontdiner Swanky' => 'Fontdiner Swanky',
						'Forum' => 'Forum',
						'Francois One' => 'Francois One',
						'Freckle Face' => 'Freckle Face',
						'Fredericka the Great' => 'Fredericka the Great',
						'Fredoka One' => 'Fredoka One',
						'Freehand' => 'Freehand',
						'Fresca' => 'Fresca',
						'Frijole' => 'Frijole',
						'Fruktur' => 'Fruktur',
						'Fugaz One' => 'Fugaz One',
						'GFS Didot' => 'GFS Didot',
						'GFS Neohellenic' => 'GFS Neohellenic',
						'Gabriela' => 'Gabriela',
						'Gafata' => 'Gafata',
						'Galdeano' => 'Galdeano',
						'Galindo' => 'Galindo',
						'Gentium Basic' => 'Gentium Basic',
						'Gentium Book Basic' => 'Gentium Book Basic',
						'Geo' => 'Geo',
						'Geostar' => 'Geostar',
						'Geostar Fill' => 'Geostar Fill',
						'Germania One' => 'Germania One',
						'Gidugu' => 'Gidugu',
						'Gilda Display' => 'Gilda Display',
						'Give You Glory' => 'Give You Glory',
						'Glass Antiqua' => 'Glass Antiqua',
						'Glegoo' => 'Glegoo',
						'Gloria Hallelujah' => 'Gloria Hallelujah',
						'Goblin One' => 'Goblin One',
						'Gochi Hand' => 'Gochi Hand',
						'Gorditas' => 'Gorditas',
						'Goudy Bookletter 1911' => 'Goudy Bookletter 1911',
						'Graduate' => 'Graduate',
						'Grand Hotel' => 'Grand Hotel',
						'Gravitas One' => 'Gravitas One',
						'Great Vibes' => 'Great Vibes',
						'Griffy' => 'Griffy',
						'Gruppo' => 'Gruppo',
						'Gudea' => 'Gudea',
						'Gurajada' => 'Gurajada',
						'Habibi' => 'Habibi',
						'Halant' => 'Halant',
						'Hammersmith One' => 'Hammersmith One',
						'Hanalei' => 'Hanalei',
						'Hanalei Fill' => 'Hanalei Fill',
						'Handlee' => 'Handlee',
						'Hanuman' => 'Hanuman',
						'Happy Monkey' => 'Happy Monkey',
						'Headland One' => 'Headland One',
						'Henny Penny' => 'Henny Penny',
						'Herr Von Muellerhoff' => 'Herr Von Muellerhoff',
						'Hind' => 'Hind',
						'Hind Siliguri' => 'Hind Siliguri',
						'Hind Vadodara' => 'Hind Vadodara',
						'Holtwood One SC' => 'Holtwood One SC',
						'Homemade Apple' => 'Homemade Apple',
						'Homenaje' => 'Homenaje',
						'IM Fell DW Pica' => 'IM Fell DW Pica',
						'IM Fell DW Pica SC' => 'IM Fell DW Pica SC',
						'IM Fell Double Pica' => 'IM Fell Double Pica',
						'IM Fell Double Pica SC' => 'IM Fell Double Pica SC',
						'IM Fell English' => 'IM Fell English',
						'IM Fell English SC' => 'IM Fell English SC',
						'IM Fell French Canon' => 'IM Fell French Canon',
						'IM Fell French Canon SC' => 'IM Fell French Canon SC',
						'IM Fell Great Primer' => 'IM Fell Great Primer',
						'IM Fell Great Primer SC' => 'IM Fell Great Primer SC',
						'Iceberg' => 'Iceberg',
						'Iceland' => 'Iceland',
						'Imprima' => 'Imprima',
						'Inconsolata' => 'Inconsolata',
						'Inder' => 'Inder',
						'Indie Flower' => 'Indie Flower',
						'Inika' => 'Inika',
						'Inknut Antiqua' => 'Inknut Antiqua',
						'Irish Grover' => 'Irish Grover',
						'Istok Web' => 'Istok Web',
						'Italiana' => 'Italiana',
						'Italianno' => 'Italianno',
						'Itim' => 'Itim',
						'Jacques Francois' => 'Jacques Francois',
						'Jacques Francois Shadow' => 'Jacques Francois Shadow',
						'Jaldi' => 'Jaldi',
						'Jim Nightshade' => 'Jim Nightshade',
						'Jockey One' => 'Jockey One',
						'Jolly Lodger' => 'Jolly Lodger',
						'Josefin Sans' => 'Josefin Sans',
						'Josefin Slab' => 'Josefin Slab',
						'Joti One' => 'Joti One',
						'Judson' => 'Judson',
						'Julee' => 'Julee',
						'Julius Sans One' => 'Julius Sans One',
						'Junge' => 'Junge',
						'Jura' => 'Jura',
						'Just Another Hand' => 'Just Another Hand',
						'Just Me Again Down Here' => 'Just Me Again Down Here',
						'Kadwa' => 'Kadwa',
						'Kalam' => 'Kalam',
						'Kameron' => 'Kameron',
						'Kanit' => 'Kanit',
						'Kantumruy' => 'Kantumruy',
						'Karla' => 'Karla',
						'Karma' => 'Karma',
						'Kaushan Script' => 'Kaushan Script',
						'Kavoon' => 'Kavoon',
						'Kdam Thmor' => 'Kdam Thmor',
						'Keania One' => 'Keania One',
						'Kelly Slab' => 'Kelly Slab',
						'Kenia' => 'Kenia',
						'Khand' => 'Khand',
						'Khmer' => 'Khmer',
						'Khula' => 'Khula',
						'Kite One' => 'Kite One',
						'Knewave' => 'Knewave',
						'Kotta One' => 'Kotta One',
						'Koulen' => 'Koulen',
						'Kranky' => 'Kranky',
						'Kreon' => 'Kreon',
						'Kristi' => 'Kristi',
						'Krona One' => 'Krona One',
						'Kurale' => 'Kurale',
						'La Belle Aurore' => 'La Belle Aurore',
						'Laila' => 'Laila',
						'Lakki Reddy' => 'Lakki Reddy',
						'Lancelot' => 'Lancelot',
						'Lateef' => 'Lateef',
						'Lato' => 'Lato',
						'League Script' => 'League Script',
						'Leckerli One' => 'Leckerli One',
						'Ledger' => 'Ledger',
						'Lekton' => 'Lekton',
						'Lemon' => 'Lemon',
						'Libre Baskerville' => 'Libre Baskerville',
						'Life Savers' => 'Life Savers',
						'Lilita One' => 'Lilita One',
						'Lily Script One' => 'Lily Script One',
						'Limelight' => 'Limelight',
						'Linden Hill' => 'Linden Hill',
						'Lobster' => 'Lobster',
						'Lobster Two' => 'Lobster Two',
						'Londrina Outline' => 'Londrina Outline',
						'Londrina Shadow' => 'Londrina Shadow',
						'Londrina Sketch' => 'Londrina Sketch',
						'Londrina Solid' => 'Londrina Solid',
						'Lora' => 'Lora',
						'Love Ya Like A Sister' => 'Love Ya Like A Sister',
						'Loved by the King' => 'Loved by the King',
						'Lovers Quarrel' => 'Lovers Quarrel',
						'Luckiest Guy' => 'Luckiest Guy',
						'Lusitana' => 'Lusitana',
						'Lustria' => 'Lustria',
						'Macondo' => 'Macondo',
						'Macondo Swash Caps' => 'Macondo Swash Caps',
						'Magra' => 'Magra',
						'Maiden Orange' => 'Maiden Orange',
						'Mako' => 'Mako',
						'Mallanna' => 'Mallanna',
						'Mandali' => 'Mandali',
						'Marcellus' => 'Marcellus',
						'Marcellus SC' => 'Marcellus SC',
						'Marck Script' => 'Marck Script',
						'Margarine' => 'Margarine',
						'Marko One' => 'Marko One',
						'Marmelad' => 'Marmelad',
						'Martel' => 'Martel',
						'Martel Sans' => 'Martel Sans',
						'Marvel' => 'Marvel',
						'Mate' => 'Mate',
						'Mate SC' => 'Mate SC',
						'Maven Pro' => 'Maven Pro',
						'McLaren' => 'McLaren',
						'Meddon' => 'Meddon',
						'MedievalSharp' => 'MedievalSharp',
						'Medula One' => 'Medula One',
						'Megrim' => 'Megrim',
						'Meie Script' => 'Meie Script',
						'Merienda' => 'Merienda',
						'Merienda One' => 'Merienda One',
						'Merriweather' => 'Merriweather',
						'Merriweather Sans' => 'Merriweather Sans',
						'Metal' => 'Metal',
						'Metal Mania' => 'Metal Mania',
						'Metamorphous' => 'Metamorphous',
						'Metrophobic' => 'Metrophobic',
						'Michroma' => 'Michroma',
						'Milonga' => 'Milonga',
						'Miltonian' => 'Miltonian',
						'Miltonian Tattoo' => 'Miltonian Tattoo',
						'Miniver' => 'Miniver',
						'Miss Fajardose' => 'Miss Fajardose',
						'Modak' => 'Modak',
						'Modern Antiqua' => 'Modern Antiqua',
						'Molengo' => 'Molengo',
						'Molle' => 'Molle',
						'Monda' => 'Monda',
						'Monofett' => 'Monofett',
						'Monoton' => 'Monoton',
						'Monsieur La Doulaise' => 'Monsieur La Doulaise',
						'Montaga' => 'Montaga',
						'Montez' => 'Montez',
						'Montserrat' => 'Montserrat',
						'Montserrat Alternates' => 'Montserrat Alternates',
						'Montserrat Subrayada' => 'Montserrat Subrayada',
						'Moul' => 'Moul',
						'Moulpali' => 'Moulpali',
						'Mountains of Christmas' => 'Mountains of Christmas',
						'Mouse Memoirs' => 'Mouse Memoirs',
						'Mr Bedfort' => 'Mr Bedfort',
						'Mr Dafoe' => 'Mr Dafoe',
						'Mr De Haviland' => 'Mr De Haviland',
						'Mrs Saint Delafield' => 'Mrs Saint Delafield',
						'Mrs Sheppards' => 'Mrs Sheppards',
						'Muli' => 'Muli',
						'Mystery Quest' => 'Mystery Quest',
						'NTR' => 'NTR',
						'Neucha' => 'Neucha',
						'Neuton' => 'Neuton',
						'New Rocker' => 'New Rocker',
						'News Cycle' => 'News Cycle',
						'Niconne' => 'Niconne',
						'Nixie One' => 'Nixie One',
						'Nobile' => 'Nobile',
						'Nokora' => 'Nokora',
						'Norican' => 'Norican',
						'Nosifer' => 'Nosifer',
						'Nothing You Could Do' => 'Nothing You Could Do',
						'Noticia Text' => 'Noticia Text',
						'Noto Sans' => 'Noto Sans',
						'Noto Serif' => 'Noto Serif',
						'Nova Cut' => 'Nova Cut',
						'Nova Flat' => 'Nova Flat',
						'Nova Mono' => 'Nova Mono',
						'Nova Oval' => 'Nova Oval',
						'Nova Round' => 'Nova Round',
						'Nova Script' => 'Nova Script',
						'Nova Slim' => 'Nova Slim',
						'Nova Square' => 'Nova Square',
						'Numans' => 'Numans',
						'Nunito' => 'Nunito',
						'Odor Mean Chey' => 'Odor Mean Chey',
						'Offside' => 'Offside',
						'Old Standard TT' => 'Old Standard TT',
						'Oldenburg' => 'Oldenburg',
						'Oleo Script' => 'Oleo Script',
						'Oleo Script Swash Caps' => 'Oleo Script Swash Caps',
						'Open Sans' => 'Open Sans',
						'Open Sans Condensed' => 'Open Sans Condensed',
						'Oranienbaum' => 'Oranienbaum',
						'Orbitron' => 'Orbitron',
						'Oregano' => 'Oregano',
						'Orienta' => 'Orienta',
						'Original Surfer' => 'Original Surfer',
						'Oswald' => 'Oswald',
						'Over the Rainbow' => 'Over the Rainbow',
						'Overlock' => 'Overlock',
						'Overlock SC' => 'Overlock SC',
						'Ovo' => 'Ovo',
						'Oxygen' => 'Oxygen',
						'Oxygen Mono' => 'Oxygen Mono',
						'PT Mono' => 'PT Mono',
						'PT Sans' => 'PT Sans',
						'PT Sans Caption' => 'PT Sans Caption',
						'PT Sans Narrow' => 'PT Sans Narrow',
						'PT Serif' => 'PT Serif',
						'PT Serif Caption' => 'PT Serif Caption',
						'Pacifico' => 'Pacifico',
						'Palanquin' => 'Palanquin',
						'Palanquin Dark' => 'Palanquin Dark',
						'Paprika' => 'Paprika',
						'Parisienne' => 'Parisienne',
						'Passero One' => 'Passero One',
						'Passion One' => 'Passion One',
						'Pathway Gothic One' => 'Pathway Gothic One',
						'Patrick Hand' => 'Patrick Hand',
						'Patrick Hand SC' => 'Patrick Hand SC',
						'Patua One' => 'Patua One',
						'Paytone One' => 'Paytone One',
						'Peddana' => 'Peddana',
						'Peralta' => 'Peralta',
						'Permanent Marker' => 'Permanent Marker',
						'Petit Formal Script' => 'Petit Formal Script',
						'Petrona' => 'Petrona',
						'Philosopher' => 'Philosopher',
						'Piedra' => 'Piedra',
						'Pinyon Script' => 'Pinyon Script',
						'Pirata One' => 'Pirata One',
						'Plaster' => 'Plaster',
						'Play' => 'Play',
						'Playball' => 'Playball',
						'Playfair Display' => 'Playfair Display',
						'Playfair Display SC' => 'Playfair Display SC',
						'Podkova' => 'Podkova',
						'Poiret One' => 'Poiret One',
						'Poller One' => 'Poller One',
						'Poly' => 'Poly',
						'Pompiere' => 'Pompiere',
						'Pontano Sans' => 'Pontano Sans',
						'Poppins' => 'Poppins',
						'Port Lligat Sans' => 'Port Lligat Sans',
						'Port Lligat Slab' => 'Port Lligat Slab',
						'Pragati Narrow' => 'Pragati Narrow',
						'Prata' => 'Prata',
						'Preahvihear' => 'Preahvihear',
						'Press Start 2P' => 'Press Start 2P',
						'Princess Sofia' => 'Princess Sofia',
						'Prociono' => 'Prociono',
						'Prosto One' => 'Prosto One',
						'Puritan' => 'Puritan',
						'Purple Purse' => 'Purple Purse',
						'Quando' => 'Quando',
						'Quantico' => 'Quantico',
						'Quattrocento' => 'Quattrocento',
						'Quattrocento Sans' => 'Quattrocento Sans',
						'Questrial' => 'Questrial',
						'Quicksand' => 'Quicksand',
						'Quintessential' => 'Quintessential',
						'Qwigley' => 'Qwigley',
						'Racing Sans One' => 'Racing Sans One',
						'Radley' => 'Radley',
						'Rajdhani' => 'Rajdhani',
						'Raleway' => 'Raleway',
						'Raleway Dots' => 'Raleway Dots',
						'Ramabhadra' => 'Ramabhadra',
						'Ramaraja' => 'Ramaraja',
						'Rambla' => 'Rambla',
						'Rammetto One' => 'Rammetto One',
						'Ranchers' => 'Ranchers',
						'Rancho' => 'Rancho',
						'Ranga' => 'Ranga',
						'Rationale' => 'Rationale',
						'Ravi Prakash' => 'Ravi Prakash',
						'Redressed' => 'Redressed',
						'Reenie Beanie' => 'Reenie Beanie',
						'Revalia' => 'Revalia',
						'Rhodium Libre' => 'Rhodium Libre',
						'Ribeye' => 'Ribeye',
						'Ribeye Marrow' => 'Ribeye Marrow',
						'Righteous' => 'Righteous',
						'Risque' => 'Risque',
						'Roboto' => 'Roboto',
						'Roboto Condensed' => 'Roboto Condensed',
						'Roboto Mono' => 'Roboto Mono',
						'Roboto Slab' => 'Roboto Slab',
						'Rochester' => 'Rochester',
						'Rock Salt' => 'Rock Salt',
						'Rokkitt' => 'Rokkitt',
						'Romanesco' => 'Romanesco',
						'Ropa Sans' => 'Ropa Sans',
						'Rosario' => 'Rosario',
						'Rosarivo' => 'Rosarivo',
						'Rouge Script' => 'Rouge Script',
						'Rozha One' => 'Rozha One',
						'Rubik' => 'Rubik',
						'Rubik Mono One' => 'Rubik Mono One',
						'Rubik One' => 'Rubik One',
						'Ruda' => 'Ruda',
						'Rufina' => 'Rufina',
						'Ruge Boogie' => 'Ruge Boogie',
						'Ruluko' => 'Ruluko',
						'Rum Raisin' => 'Rum Raisin',
						'Ruslan Display' => 'Ruslan Display',
						'Russo One' => 'Russo One',
						'Ruthie' => 'Ruthie',
						'Rye' => 'Rye',
						'Sacramento' => 'Sacramento',
						'Sahitya' => 'Sahitya',
						'Sail' => 'Sail',
						'Salsa' => 'Salsa',
						'Sanchez' => 'Sanchez',
						'Sancreek' => 'Sancreek',
						'Sansita One' => 'Sansita One',
						'Sarala' => 'Sarala',
						'Sarina' => 'Sarina',
						'Sarpanch' => 'Sarpanch',
						'Satisfy' => 'Satisfy',
						'Scada' => 'Scada',
						'Scheherazade' => 'Scheherazade',
						'Schoolbell' => 'Schoolbell',
						'Seaweed Script' => 'Seaweed Script',
						'Sevillana' => 'Sevillana',
						'Seymour One' => 'Seymour One',
						'Shadows Into Light' => 'Shadows Into Light',
						'Shadows Into Light Two' => 'Shadows Into Light Two',
						'Shanti' => 'Shanti',
						'Share' => 'Share',
						'Share Tech' => 'Share Tech',
						'Share Tech Mono' => 'Share Tech Mono',
						'Shojumaru' => 'Shojumaru',
						'Short Stack' => 'Short Stack',
						'Siemreap' => 'Siemreap',
						'Sigmar One' => 'Sigmar One',
						'Signika' => 'Signika',
						'Signika Negative' => 'Signika Negative',
						'Simonetta' => 'Simonetta',
						'Sintony' => 'Sintony',
						'Sirin Stencil' => 'Sirin Stencil',
						'Six Caps' => 'Six Caps',
						'Skranji' => 'Skranji',
						'Slabo 13px' => 'Slabo 13px',
						'Slabo 27px' => 'Slabo 27px',
						'Slackey' => 'Slackey',
						'Smokum' => 'Smokum',
						'Smythe' => 'Smythe',
						'Sniglet' => 'Sniglet',
						'Snippet' => 'Snippet',
						'Snowburst One' => 'Snowburst One',
						'Sofadi One' => 'Sofadi One',
						'Sofia' => 'Sofia',
						'Sonsie One' => 'Sonsie One',
						'Sorts Mill Goudy' => 'Sorts Mill Goudy',
						'Source Code Pro' => 'Source Code Pro',
						'Source Sans Pro' => 'Source Sans Pro',
						'Source Serif Pro' => 'Source Serif Pro',
						'Special Elite' => 'Special Elite',
						'Spicy Rice' => 'Spicy Rice',
						'Spinnaker' => 'Spinnaker',
						'Spirax' => 'Spirax',
						'Squada One' => 'Squada One',
						'Sree Krushnadevaraya' => 'Sree Krushnadevaraya',
						'Stalemate' => 'Stalemate',
						'Stalinist One' => 'Stalinist One',
						'Stardos Stencil' => 'Stardos Stencil',
						'Stint Ultra Condensed' => 'Stint Ultra Condensed',
						'Stint Ultra Expanded' => 'Stint Ultra Expanded',
						'Stoke' => 'Stoke',
						'Strait' => 'Strait',
						'Sue Ellen Francisco' => 'Sue Ellen Francisco',
						'Sumana' => 'Sumana',
						'Sunshiney' => 'Sunshiney',
						'Supermercado One' => 'Supermercado One',
						'Sura' => 'Sura',
						'Suranna' => 'Suranna',
						'Suravaram' => 'Suravaram',
						'Suwannaphum' => 'Suwannaphum',
						'Swanky and Moo Moo' => 'Swanky and Moo Moo',
						'Syncopate' => 'Syncopate',
						'Tangerine' => 'Tangerine',
						'Taprom' => 'Taprom',
						'Tauri' => 'Tauri',
						'Teko' => 'Teko',
						'Telex' => 'Telex',
						'Tenali Ramakrishna' => 'Tenali Ramakrishna',
						'Tenor Sans' => 'Tenor Sans',
						'Text Me One' => 'Text Me One',
						'The Girl Next Door' => 'The Girl Next Door',
						'Tienne' => 'Tienne',
						'Tillana' => 'Tillana',
						'Timmana' => 'Timmana',
						'Tinos' => 'Tinos',
						'Titan One' => 'Titan One',
						'Titillium Web' => 'Titillium Web',
						'Trade Winds' => 'Trade Winds',
						'Trocchi' => 'Trocchi',
						'Trochut' => 'Trochut',
						'Trykker' => 'Trykker',
						'Tulpen One' => 'Tulpen One',
						'Ubuntu' => 'Ubuntu',
						'Ubuntu Condensed' => 'Ubuntu Condensed',
						'Ubuntu Mono' => 'Ubuntu Mono',
						'Ultra' => 'Ultra',
						'Uncial Antiqua' => 'Uncial Antiqua',
						'Underdog' => 'Underdog',
						'Unica One' => 'Unica One',
						'UnifrakturCook' => 'UnifrakturCook',
						'UnifrakturMaguntia' => 'UnifrakturMaguntia',
						'Unkempt' => 'Unkempt',
						'Unlock' => 'Unlock',
						'Unna' => 'Unna',
						'VT323' => 'VT323',
						'Vampiro One' => 'Vampiro One',
						'Varela' => 'Varela',
						'Varela Round' => 'Varela Round',
						'Vast Shadow' => 'Vast Shadow',
						'Vesper Libre' => 'Vesper Libre',
						'Vibur' => 'Vibur',
						'Vidaloka' => 'Vidaloka',
						'Viga' => 'Viga',
						'Voces' => 'Voces',
						'Volkhov' => 'Volkhov',
						'Vollkorn' => 'Vollkorn',
						'Voltaire' => 'Voltaire',
						'Waiting for the Sunrise' => 'Waiting for the Sunrise',
						'Wallpoet' => 'Wallpoet',
						'Walter Turncoat' => 'Walter Turncoat',
						'Warnes' => 'Warnes',
						'Wellfleet' => 'Wellfleet',
						'Wendy One' => 'Wendy One',
						'Wire One' => 'Wire One',
						'Work Sans' => 'Work Sans',
						'Yanone Kaffeesatz' => 'Yanone Kaffeesatz',
						'Yantramanav' => 'Yantramanav',
						'Yellowtail' => 'Yellowtail',
						'Yeseva One' => 'Yeseva One',
						'Yesteryear' => 'Yesteryear',
						'Zeyada' => 'Zeyada',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_565ca881b358d',
					'label' => 'Variants',
					'name' => 'variants',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 33,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						100 => 100,
						'100italic' => '100 italic',
						200 => 200,
						'200italic' => '200 italic',
						300 => 300,
						'300italic' => '300 italic',
						'regular' => 400,
						'italic' => '400 italic',
						500 => 500,
						'500italic' => '500 italic',
						600 => 600,
						'600italic' => '600 italic',
						700 => 700,
						'700italic' => '700 italic',
						800 => 800,
						'800italic' => '800 italic',
						900 => 900,
						'900italic' => '900 italic',
					),
					'default_value' => array (
					),
					'layout' => 'horizontal',
					'toggle' => 1,
				),
			),
		),
		array (
			'key' => 'field_562e5bcbf0cd5',
			'label' => 'Add typekit fonts?',
			'name' => 'add_typekit_fonts',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_562e5be0f0cd6',
			'label' => 'Typekit ID',
			'name' => 'typekit_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_562e5bcbf0cd5',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_562e5c10f0cd7',
			'label' => 'Font Family Names',
			'name' => 'typekit_fonts',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_562e5bcbf0cd5',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Font Family',
			'sub_fields' => array (
				array (
					'key' => 'field_562e5f4b13e57',
					'label' => 'Display Name',
					'name' => 'typekit_font',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_562e5c23f0cd8',
					'label' => 'CSS Name',
					'name' => 'css_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_56265e29e9709',
			'label' => '404 Header Image',
			'name' => '404_header_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'theme_image_preview',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_55d4c8be4b506',
			'label' => 'Header Options',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-tab field_key-field_55d4c8be4b506',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_560ec99f29270',
			'label' => 'Header Type',
			'name' => 'header_type',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Top Menu' => 'Top Menu',
				'Left Side Menu' => 'Left Side Menu',
				'Right Side Menu' => 'Right Side Menu',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_572279229a959',
			'label' => 'Top Header Position',
			'name' => 'top_header_position',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'header-no-overlap' => 'Site header does not overlap page header',
				'header-overlap' => 'Site header overlaps page header',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_5604338a4ef10',
			'label' => 'Is header in grid?',
			'name' => 'is_header_in_grid',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560ec99f29270',
						'operator' => '==',
						'value' => 'Top Menu',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_55d4c8cd4b507',
			'label' => 'Header Background Color',
			'name' => 'header_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d4c8cd4b507',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_55e870ab71ed8',
			'label' => 'Header Background Opacity',
			'name' => 'header_background_opacity',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-number field_key-field_55e870ab71ed8',
				'id' => '',
			),
			'default_value' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 0,
			'max' => 1,
			'step' => '0.05',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5640d20d9edeb',
			'label' => 'Logo Height',
			'name' => 'logo_height',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560ec99f29270',
						'operator' => '==',
						'value' => 'Top Menu',
					),
					array (
						'field' => 'field_5605b94321d7d',
						'operator' => '==',
						'value' => 'center',
					),
					array (
						'field' => 'field_5640cb7f7749f',
						'operator' => '==',
						'value' => 'top',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => '',
			'max' => '',
			'step' => 1,
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55f30b4e7e257',
			'label' => 'Desktop Header Height',
			'name' => 'desktop_header_height',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-number field_key-field_55f30b4e7e257',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56f01ecbd8ab4',
			'label' => 'Use Sticky Header?',
			'name' => 'sticky_header',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560ec99f29270',
						'operator' => '==',
						'value' => 'Top Menu',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-number field_key-field_55f30b4e7e257',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_56f01f4fd8ab5',
			'label' => 'Sticky Header Logo',
			'name' => 'sticky_header_logo',
			'type' => 'file',
			'instructions' => 'If you want a different logo for a smaller sticky header, upload one here',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56f01ecbd8ab4',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-number field_key-field_55f30b4e7e257',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_56f01fa1d8ab6',
			'label' => 'Sticky Header Height',
			'name' => 'sticky_header_height',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_56f01ecbd8ab4',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-number field_key-field_55f30b4e7e257',
				'id' => '',
			),
			'default_value' => 50,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5604357499149',
			'label' => 'Mobile Header Height',
			'name' => 'mobile_header_height',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-number field_key-field_55f30b4e7e257',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5605b94321d7d',
			'label' => 'Logo Position',
			'name' => 'logo_position',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'left' => 'left',
				'center' => 'center',
				'right' => 'right',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_5640cb7f7749f',
			'label' => 'Center Logo Menu Type',
			'name' => 'center_logo_menu_type',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5605b94321d7d',
						'operator' => '==',
						'value' => 'center',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'top' => 'Centered above menu',
				'divided' => 'In between two menus',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_560433b34ef11',
			'label' => 'Hide menu on desktop?',
			'name' => 'hide_menu_on_desktop',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Will open with a button',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5665e7433c1ef',
			'label' => 'Mobile Menu Item Divider Color',
			'name' => 'mobile_menu_item_divider_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#FFFFFF',
		),
		array (
			'key' => 'field_5665e4d43c1ea',
			'label' => 'Menu Icon Top Bar Background Color',
			'name' => 'menu_icon_top_bar_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#FFFFFF',
		),
		array (
			'key' => 'field_5665e5123c1eb',
			'label' => 'Menu Icon Middle Bar Background Color',
			'name' => 'menu_icon_middle_bar_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#FFFFFF',
		),
		array (
			'key' => 'field_5665e5293c1ec',
			'label' => 'Menu Icon Bottom Bar Background Color',
			'name' => 'menu_icon_bottom_bar_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#FFFFFF',
		),
		array (
			'key' => 'field_5665e53d3c1ed',
			'label' => 'Menu Icon Text Color Color',
			'name' => 'menu_icon_text_color_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#FFFFFF',
		),
		array (
			'key' => 'field_560eca6029271',
			'label' => 'Menu Background Color',
			'name' => 'menu_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_55d4c9004b509',
			'label' => 'Menu Link Color',
			'name' => 'menu_link_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d4c9004b509',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_55d4ccd62c1e6',
			'label' => 'Menu Link Active Color',
			'name' => 'menu_link_active_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d4ccd62c1e6',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_55d4c9204b50a',
			'label' => 'Menu Font Size',
			'name' => 'menu_font_size',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-number field_key-field_55d4c9204b50a',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 12,
			'max' => 50,
			'step' => 1,
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5665e5b63c1ee',
			'label' => 'Menu Line Height',
			'name' => 'menu_line_height',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-number field_key-field_55d4c9204b50a',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => '',
			'max' => '',
			'step' => 1,
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5602e24562fc3',
			'label' => 'Menu Font Family',
			'name' => 'menu_font_family',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Roboto' => 'Roboto',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_55d616e76456c',
			'label' => 'Footer Options',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-tab field_key-field_55d616e76456c',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_55d617006456d',
			'label' => 'Footer Top Background Color',
			'name' => 'footer_top_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d617006456d',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_55d617196456e',
			'label' => 'Footer Top Text Color',
			'name' => 'footer_top_text_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d617196456e',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_55d6172c6456f',
			'label' => 'Footer Top Link Color',
			'name' => 'footer_top_link_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d6172c6456f',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_55d6173a64570',
			'label' => 'Footer Top Link Hover Color',
			'name' => 'footer_top_link_hover_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55d6173a64570',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_55e4a26589202',
			'label' => 'Footer Bottom Background Color',
			'name' => 'footer_bottom_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55e4a26589202',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_55e4a26989203',
			'label' => 'Footer Bottom Text Color',
			'name' => 'footer_bottom_text_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55e4a26989203',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_55e4a26a89204',
			'label' => 'Footer Bottom Link Color',
			'name' => 'footer_bottom_link_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55e4a26a89204',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_55e4a26c89205',
			'label' => 'Footer Bottom Link Hover Color',
			'name' => 'footer_bottom_link_hover_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55e4a26c89205',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_5718ff8fcd62e',
			'label' => 'Footer Logo',
			'name' => 'footer_logo',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'field_type-color_picker field_key-field_55e4a26c89205',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_56043ca610408',
			'label' => 'Typography',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_560f06f06f1ba',
			'label' => 'Default Font Family',
			'name' => 'default_font_family',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Roboto' => 'Roboto',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_56043cbf10409',
			'label' => 'Headings Font Family',
			'name' => 'headings_font_family',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Roboto' => 'Roboto',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_56043cd61040a',
			'label' => 'Headings Font Color',
			'name' => 'headings_font_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_56043cf61040b',
			'label' => 'Headings Text Transform',
			'name' => 'headings_text_transform',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'none' => 'none',
				'uppercase' => 'uppercase',
				'lowercase' => 'lowercase',
				'capitalize' => 'capitalize',
			),
			'default_value' => array (
			),
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_56043d281040c',
			'label' => 'Headings Line Height',
			'name' => 'headings_line_height',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '0.8',
			'max' => 2,
			'step' => '0.05',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56043d461040d',
			'label' => 'Headings Font Weight',
			'name' => 'headings_font_weight',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				400 => 400,
				100 => 100,
				300 => 300,
				500 => 500,
				600 => 600,
				700 => 700,
				800 => 800,
				900 => 900,
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_56043d901040e',
			'label' => 'Paragraph Font Family',
			'name' => 'paragraph_font_family',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Roboto' => 'Roboto',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_56043dab1040f',
			'label' => 'Paragraph Font Color',
			'name' => 'paragraph_font_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#000000',
		),
		array (
			'key' => 'field_56043dc610410',
			'label' => 'Paragraph Text Transform',
			'name' => 'paragraph_text_transform',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'none' => 'none',
				'uppercase' => 'uppercase',
				'lowercase' => 'lowercase',
				'capitalize' => 'capitalize',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_56043dda10411',
			'label' => 'Paragraph Line Height',
			'name' => 'paragraph_line_height',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '0.5',
			'max' => 2,
			'step' => '0.05',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56043e0610413',
			'label' => 'Paragraph Font Weight',
			'name' => 'paragraph_font_weight',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				400 => 400,
				100 => 100,
				300 => 300,
				500 => 500,
				600 => 600,
				700 => 700,
				800 => 800,
				900 => 900,
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_5626690ae235d',
			'label' => 'Link Text Color',
			'name' => 'link_text_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_5626691de235e',
			'label' => 'Link Text Hover Color',
			'name' => 'link_text_hover_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_5638f0365f870',
			'label' => 'Blog',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5638f04c5f871',
			'label' => 'Excerpt Length',
			'name' => 'excerpt_length',
			'type' => 'number',
			'instructions' => 'How many words do you want the post excerpts to display?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 30,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 10,
			'max' => '',
			'step' => 1,
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5638f0b75f872',
			'label' => 'Finish sentence',
			'name' => 'finish_sentence',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Check this if you want to finish the sentence of the excerpt (No weird cuts).',
			'default_value' => 1,
		),
		array (
			'key' => 'field_5638f1485f875',
			'label' => 'Pagination Item Background Color',
			'name' => 'pagination_item_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#CCCCCC',
		),
		array (
			'key' => 'field_5638f17d5f876',
			'label' => 'Pagination Item Text Color',
			'name' => 'pagination_item_text_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#000000',
		),
		array (
			'key' => 'field_5638f0e75f873',
			'label' => 'Pagination Current Item Background Color',
			'name' => 'pagination_current_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#000000',
		),
		array (
			'key' => 'field_5638f1295f874',
			'label' => 'Pagination Current Item Text Color',
			'name' => 'pagination_current_text_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#FFFFFF',
		),
		array (
			'key' => 'field_564a234a7b6c1',
			'label' => 'Extras',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_573e0c3993926',
			'label' => 'Copyright Text',
			'name' => 'copyright_text',
			'type' => 'text',
			'instructions' => 'Use instead of default copyright txt ( [company name] © [current year] ). Will still add copyright symbol and current year at the end',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 100,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_564a24777b6c9',
			'label' => 'Scroll Button Width',
			'name' => 'scroll_button_width',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 60,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_564a23da7b6c3',
			'label' => 'Scroll Button Border Width',
			'name' => 'scroll_button_border_width',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 3,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_564a24a77b6ca',
			'label' => 'Scroll Button Distance from Bottom',
			'name' => 'scroll_button_bottom',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 10,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_564a2ab4176e0',
			'label' => 'Scroll Button Icon Font Size',
			'name' => 'scroll_button_icon_font_size',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 55,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_564a24d07b6cb',
			'label' => 'Scroll Button Distance from Right',
			'name' => 'scroll_button_right',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 10,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_564a23af7b6c2',
			'label' => 'Scroll Button Border Color',
			'name' => 'scroll_button_border_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#231F20',
		),
		array (
			'key' => 'field_564a23fa7b6c4',
			'label' => 'Scroll Button Background Color',
			'name' => 'scroll_button_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_564a241a7b6c5',
			'label' => 'Scroll Button Icon Color',
			'name' => 'scroll_button_icon_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#231F20',
		),
		array (
			'key' => 'field_564a243d7b6c6',
			'label' => 'Scroll Button Hover Border Color',
			'name' => 'scroll_button_hover_border_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#E1E1E1',
		),
		array (
			'key' => 'field_564a245d7b6c7',
			'label' => 'Scroll Button Hover Background Color',
			'name' => 'scroll_button_hover_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#E1E1E1',
		),
		array (
			'key' => 'field_564a246a7b6c8',
			'label' => 'Scroll Button Hover Icon Color',
			'name' => 'scroll_button_hover_icon_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_564a25ae7b6cd',
			'label' => 'Sadie Effect Gradient Top Color',
			'name' => 'sadie_effect_gradient_top_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_564a25f37b6cf',
			'label' => 'Sadie Effect Gradient Top Color Opacity',
			'name' => 'sadie_effect_gradient_top_color_opacity',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'default_value' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 0,
			'max' => 1,
			'step' => '0.01',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_564a258b7b6cc',
			'label' => 'Sadie Effect Gradient Bottom Color',
			'name' => 'sadie_effect_gradient_bottom_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_564a25ce7b6ce',
			'label' => 'Sadie Effect Gradient Bottom Color Opacity',
			'name' => 'sadie_effect_gradient_bottom_color_opacity',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'default_value' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 0,
			'max' => 1,
			'step' => '0.01',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-general-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif; ?>